<dependencies>
    <dependency>
        <groupId>com.squareup.okhttp3</groupId>
        <artifactId>okhttp</artifactId>
        <version>4.12.0</version>
    </dependency>

    <dependency>
        <groupId>com.launchdarkly</groupId>
        <artifactId>okhttp-eventsource</artifactId>
        <version>4.1.0</version>
    </dependency>
</dependencies>
